docs(grid): Toolbar topic add export visaulization
IgniteUI/igniteui-docfx pull request #2205
Opened 2020-09-02 10:43 UTC by astaev

Closes #2187 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2020-09-02 15:37 UTC, DiyanDimitrov requested changes
Remove the topic section for hierarchical grid since we do not officially support exporting in hierarchical grid.

2020-09-02 15:37 UTC, DiyanDimitrov commented on en/components/grids_templates/toolbar.md
> +#### Exporting Indicator
Move this section right after the **Customizing the Export** one.

2020-09-04 09:15 UTC, DiyanDimitrov approved these changes

2020-09-04 12:53 UTC, onlyexeption commented on en/components/grids_templates/toolbar.md
> +<button data-localize="codesandbox" disabled class="codesandbox-btn" data-iframe-id="excel-export-sample1-iframe"           data-demos-base-url="{environment:demosBaseUrl}">view on codesandbox</butto
remove extra space

2020-09-04 13:52 UTC, onlyexeption approved these changes

2020-09-04 13:52 UTC, onlyexeption submitted a review, later dismissed

2020-09-08 13:09 UTC, DiyanDimitrov approved these changes

2020-09-08 13:10 UTC, merged