Valadzhov/date picker new label 8086
IgniteUI/igniteui-docfx pull request #2213
Opened 2020-09-09 09:07 UTC by valadzhov

Adding information about the new label implementation.

Closes #8086

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2020-09-11 08:12 UTC, Lipata approved these changes

2020-09-18 09:54 UTC, Lipata requested changes

2020-09-18 09:54 UTC, Lipata commented on en/components/date_picker.md
> +By placing an `igxlabel` inside a `<label>` tag nested in the component, the default label can be changed to a custom one:
```suggestion
Using the `igxLabel` directive, the default label can be changed to a custom one:
```

2020-09-18 09:54 UTC, Lipata commented on en/components/date_picker.md
> +> Currently the `label` and `labelVisibility` properties are in the process of being deprecated. During this period if `labelVisibility` is set to `false` and a custom label is not provided then a de
```suggestion
> Currently the `label` and `labelVisibility` properties are deprecated. Until they are removed, if `labelVisibility` is set to `false` and a custom label is not provided then a default `Date` label will be set.
```

2020-09-18 10:02 UTC, valadzhov commented on en/components/date_picker.md
> +By placing an `igxlabel` inside a `<label>` tag nested in the component, the default label can be changed to a custom one:
Changed to the suggestion.

2020-09-18 10:10 UTC, Lipata submitted a review, later dismissed

2020-09-28 08:25 UTC, Lipata approved these changes

2020-09-28 09:15 UTC, merged