refactor (main grid pages): Content update -vnext
IgniteUI/igniteui-docfx pull request #2361
Opened 2020-10-29 16:29 UTC by dobromirts

Closes # https://github.com/IgniteUI/trial-watermark/issues/85

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2020-10-30 11:57 UTC, HristoP96 requested changes
Can you change also the _Tree cells_ header to **Tree Cells** and the _Child collection_ header to **Child Collection**

2020-10-30 11:57 UTC, HristoP96 commented on en/components/treegrid/tree-grid.md
> +### Initial expansion depth
```suggestion
### Initial Expansion Depth
```

2020-10-30 11:57 UTC, HristoP96 commented on en/components/treegrid/tree-grid.md
> +### Defining a color palette
```suggestion
### Defining a Color Palette
```

2020-11-05 15:17 UTC, zdrawku approved these changes

2020-11-05 15:18 UTC, merged