Changes from AngularDocFX_EN
IgniteUI/igniteui-docfx pull request #2440
Opened 2020-11-18 08:03 UTC by ESShared

2020-11-24 19:15 UTC, HUSSAR-mtrela commented
@zdrawku hold on merging this PR as we are still working on new topics and SEO improvements of TOC for chart topics

2020-11-25 15:34 UTC, HristoP96 requested changes
All of the links are having incorrect environment variable - **environment:dvapibaseurl**, which shuold be _environment:dvApiBaseUrl_

2020-11-25 20:21 UTC, HUSSAR-mtrela commented
@HristoP96 those links should be fixed now

2020-11-26 09:10 UTC, zdrawku approved these changes

2020-11-26 09:10 UTC, HristoP96 approved these changes

2020-11-26 09:14 UTC, merged