Rename buttonGroup topic - vnext
IgniteUI/igniteui-docfx pull request #2486
Opened 2020-12-07 09:09 UTC by dobromirts

Closes #2479 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2020-12-07 14:44 UTC, HristoP96 requested changes
The list.md and button.md topics referer to the buttonGroup.md (not in all versions), which shoul be changed:
![image](https://user-images.githubusercontent.com/25771040/101364567-63ceea80-38ab-11eb-9aa0-ef1db8b2c510.png)

@zdrawku Given this should we add redirect for this topic?

2020-12-08 13:44 UTC, zdrawku commented
I am not sure whether there would be any effect from the redirect - I believe there is a rule that apply `lower-case`  to the urls

2020-12-08 13:49 UTC, HristoP96 approved these changes

2020-12-08 13:49 UTC, HristoP96 submitted a review, later dismissed

2020-12-08 13:58 UTC, zdrawku commented
On a second though, lets add the redirect for insurance

2020-12-08 14:41 UTC, HristoP96 approved these changes

2020-12-09 10:57 UTC, zdrawku approved these changes

2020-12-09 10:57 UTC, merged