feat(Tabs): Adding a section for IgxBottomNav and IgxTabs changes in Update Guide.
IgniteUI/igniteui-docfx pull request #2706
Opened 2021-04-12 14:26 UTC by gedinakova

Closes #2696 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-04-13 13:18 UTC, astaev commented on en/components/general/update-guide.md
> +        * The `type` property, with its contentFit and fixed options, is no longer available. The header sizing & positioning mode is currently controlled by the `tabAlignment` input property which a
We can mention that old contentFit now corresponds to current start(not matter that it's the default one).

2021-04-13 13:30 UTC, astaev commented on en/components/general/update-guide.md
> +
Just mention about routerLink directive - it's now set on the header but migrations should update it.

2021-04-14 07:28 UTC, DiyanDimitrov requested changes

2021-04-14 07:28 UTC, DiyanDimitrov commented on en/components/general/update-guide.md
> +    * The `tabItemSelected` and `tabItemDeselected` events were removed. We introduced three new events, `selectedIndexChanging`, `selectedIndexChange` and `selectedItemChange`, which provide more fl
IMO We should split those for the two components. I am not sure those were called the same for the tabs and bottom nav components. For example the events of the bottom nav were called `onTabSelected`/`onTabDeselected`.

2021-04-15 15:18 UTC, DiyanDimitrov commented on en/components/general/update-guide.md
> +### `IgxBottomNav` and `IgxTabs`
I don't like them bold either 😄 It looks strange to have bold text in the header which already looks bold.

2021-04-15 16:35 UTC, astaev approved these changes

2021-04-16 09:28 UTC, DiyanDimitrov approved these changes

2021-04-16 09:29 UTC, merged