feat(themes): full theming example with bootstrap
IgniteUI/igniteui-docfx pull request #2716
Opened 2021-04-15 07:56 UTC by SisIvanova

Closes # 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-04-15 13:48 UTC, simeonoff requested changes

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +At this point your applications is ready to use the NG Bootstrap components. You can find more information about using Bootstrap library at their [`official documentation`](https://ng-bootstrap.githu
```suggestion
At this point your applications is ready to use the NG Bootstrap components. You can find more information about using the Bootstrap library at their [`official documentation`](https://ng-bootstrap.github.io/#/getting-started).
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +To install the Ignite UI for Angular package, along with all of its dependencies, font imports and styles references to your project, run the following command:
```suggestion
To install the Ignite UI for Angular package along with all of its dependencies, font imports, and styles references, run the following command in your project,: 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +Finally, we inserted an igx `icon button` in the top right corner, that changes the color palette for the whole app:
```suggestion
Finally, we inserted an Ignite UI for Angular `icon button` in the top right corner, that changes the theme of the whole app: 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +The Bootstrap library makes use of a sass map called [`$theme-colors`](https://getbootstrap.com/docs/4.0/getting-started/theming/#theme-colors) to provide a palette composed of eight colors:
```suggestion
The Bootstrap library makes use of a Sass map called [`$theme-colors`](https://getbootstrap.com/docs/4.0/getting-started/theming/#theme-colors) to provide a palette composed of eight colors:
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +On the other hand, the Ignite UI [`igx-palette`]({environment:sassApiUrl}/index.html#function-igx-palette) function generates a color palette map including `primary`, `secondary`, `grays`, `info`, `s
```suggestion
Ignite UI for Angular's [`igx-palette`]({environment:sassApiUrl}/index.html#function-igx-palette) function generates a color palette map including `primary`, `secondary`, `grays`, `info`, `success`, `warn`, and `error` colors and their color variants. Our predefined bootstrap palette in turn consists of seven colors: 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +As you can see most of the colors in their palette overlap the colors in the palettes of Ignite UI. Thus, we can simply map the Bootstrap theme colors with our light or dark bootstrap palette colors.
```suggestion
As you can see most of the colors in the Bootstrap palette overlap with the colors defined the Bootstrap palette of Ignite UI for Angular. Hence, we can simply map the Bootstrap theme colors to our light or dark bootstrap palette colors. 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +First, we are going to define Sass variables for the [`$light-bootstrap-palette`]({environment:sassApiUrl}/index.html#variable-light-bootstrap-palette) colors:
```suggestion
First, we are going to define Sass variables that extract values from the [`$light-bootstrap-palette`]({environment:sassApiUrl}/index.html#variable-light-bootstrap-palette):
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +// Creating Sass variables for its primary and secondary colors
```suggestion
// Creating Sass variables for primary and secondary colors
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +>Visit our [`palettes with sass`](../sass/palettes.md) section to discover more about the palettes provided by Ignite UI for Angular and learn how to create a new one.
```suggestion
>Visit our [`palettes with Sass`](../sass/palettes.md) section to discover more about the palettes provided by Ignite UI for Angular and learn how to create a new one.
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +In order to switch between `light` and `dark` mode, we are adding a custom class to the `host` element which will be changed on button click event. In our stylesheet file, we are going to include dif
```suggestion
In order to switch between `light` and `dark` mode, we are adding a custom class to the `host` element which will be changed on button click. In our stylesheet file, we are going to include different color palettes scoped to each class.
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +The Ignite UI for Angular comes in with a predefined theme inspired by [Bootstrap 4](https://getbootstrap.com/) library. To use it, first, you have to include our `igx-core` mixin and then our built-
```suggestion
Ignite UI for Angular comes with predefined themes inspired by the [Bootstrap 4](https://getbootstrap.com/) library. To use them, first, you have to include our `igx-core` mixin and then our built-in theme mixin - [igx-bootstrap-light-theme]({environment:sassApiUrl}/index.html#mixin-igx-bootstrap-light-theme). We will also make use of our predefined bootstrap palette - [$light-bootstrap-palette]({environment:sassApiUrl}/index.html#variable-light-bootstrap-palette). 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +Along with including the themes, at this point, we have to modify the bootstrap `$theme-colors` map with our sass variables created earlier.
```suggestion
At this point we have to modify the Bootstrap `$theme-colors` map with the Sass variables we created earlier.
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +Lastly, we need to import the bootstrap library - *always import it at the end!*
```suggestion
Lastly, we need to import the Bootstrap library - *always import it at the end!*
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +            // Importing Bootstrap SCSS file
```suggestion
            // Importing Bootstrap .scss file
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +For our dark variant of the application we are going to use our newly created `$custom-dark-palette` so we have to include it in the `dark class` styles and also modify the `$theme-colors` map with t
```suggestion
For our dark variant, we are going to use our newly created `$custom-dark-palette`. We have to include it in the `dark` class styles and also modify the `$theme-colors` map with the new values. 
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +All the colors in the Ignite UI components come from the passed palette, therefore they fit nicely in the dark mode without any additional adjustments. However, we have to do some more styling change
```suggestion
All components in Ignite UI for Angular use colors from the passed palette, therefore they fit nicely in the dark mode without any additional adjustments. However, we have to do some more styling changes for the ng-bootstrap components:
```

2021-04-15 13:48 UTC, simeonoff commented on en/components/themes/misc/bootstrap-theming.md
> +Ignite UI for Angular exposes four default type scales for each of its themes, which can be used inside the [`igx-typography`]({environment:sassApiUrl}/index.html#mixin-igx-typography) mixin to defin
```suggestion
Ignite UI for Angular exposes four default type scales for each of its themes, which can be used inside the [`igx-typography`]({environment:sassApiUrl}/index.html#mixin-igx-typography) mixin to define the global typography styles of an application. In our example, we are going to apply the bootstrap predifined `typeface` and `type-scale` but you can create custom ones if you wish. 
```

2021-04-16 07:15 UTC, simeonoff approved these changes

2021-04-16 08:29 UTC, StefanIvanov commented
@aatanasov2 will help us with the SEO since this topic can draw lots of traffic to the docs and samples :)

2021-04-19 06:47 UTC, merged