Fixed ESF and Tabs broken links - vNext
IgniteUI/igniteui-docfx pull request #2744
Opened 2021-04-22 14:42 UTC by igdmdimitrov

Closes #2743 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-04-22 15:45 UTC, gedinakova approved these changes

2021-04-22 15:54 UTC, gedinakova requested changes

2021-04-22 15:54 UTC, gedinakova commented on en/components/grids_templates/excel-style-filtering.md
> +- [`IgxExcelStyleColumnOperationsTemplateDirective`]({environment:angularApiUrl}/classes/igxexcelstylecolumnoperationstemplatedirective.html) - re-templates the area with all column operations like s
I'd rather remove the links to these two directives. They have no API members so the page we link to doesn't really bring any value.

2021-04-22 15:54 UTC, gedinakova commented on en/components/tabs.md
> +We set the tabs header by providing content to `igx-tab-header`. To set the tab's name we simply add a span with [`igxTabHeaderLabel`]({environment:angularApiUrl}/classes/igxtabheaderlabeldirective.h
Same as above, let's remove the link to igxTabHeaderLabel directive as well. We just need to know its name.

2021-04-22 15:54 UTC, gedinakova commented on en/components/tabs.md
> +First, add the Material Icons in your 'styles.scss' file in the main application folder. Next, add `igx-icon` with [`igxTabHeaderIcon`]({environment:angularApiUrl}/classes/igxtabheadericondirective.h
Same as above.

2021-04-23 08:28 UTC, gedinakova requested changes
There is one more broken link - "If setting the labels and icons is not enough, you can also provide your own custom content directly between **igx-tab-header** tags."

2021-04-23 08:49 UTC, igdmdimitrov commented
> There is one more broken link - "If setting the labels and icons is not enough, you can also provide your own custom content directly between **igx-tab-header** tags."

fixed

2021-04-23 15:12 UTC, gedinakova approved these changes

2021-04-23 15:13 UTC, merged