Ibarakov/issue 2856
IgniteUI/igniteui-docfx pull request #2862
Opened 2021-06-17 13:15 UTC by onlyexeption

Closes #2856 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-06-18 10:55 UTC, gedinakova requested changes

2021-06-18 10:55 UTC, gedinakova commented on en/components/grids_templates/export-excel.md
> +It is now possible to export @@igComponent with defined [multi-column headers](../multi-column-headers). All headers will be reflected in the exported excel file as they are displayed in the @@igComp
Please, add information about the ignoreMultiColumnHeaders option.

2021-07-02 14:52 UTC, gedinakova submitted a review, later dismissed

2021-07-09 11:43 UTC, kdinev requested changes

2021-07-09 11:43 UTC, kdinev commented on en/components/grids_templates/export-excel.md
> +It is now possible to export @@igComponent with defined [multi-column headers](../multi-column-headers). All headers will be reflected in the exported excel file as they are displayed in the @@igComp
```suggestion
It is now possible to export @@igComponent with defined [multi-column headers](multi-column-headers.md). All headers will be reflected in the exported excel file as they are displayed in the @@igComponent. If you want to exclude the defined multi-column headers from the exported data you can set the [exporter option]({environment:angularApiUrl}/classes/igxexporteroptionsbase.html) [ignoreMultiColumnHeaders]({environment:angularApiUrl}/classes/igxexporteroptionsbase.html#ignoremulticolumnheaders) to `true`.
```

2021-07-09 12:01 UTC, kdinev approved these changes

2021-07-09 12:01 UTC, merged