Updating grid row drag topic
IgniteUI/igniteui-docfx pull request #2914
Opened 2021-07-22 08:58 UTC by dafo

Closes #2788  

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [x] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [x] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-07-22 09:06 UTC, dafo commented
A thing I would like to discuss is the title of the first of the added sections "Getting advantage of knowing the target row while dragging". I am not sure if this is the best title, maybe other options are something like "More opportunities to customize row dragging UX", "Changing drag ghost and displaying a drop indicator based on cursor position".

2021-07-22 12:56 UTC, ViktorSlavov requested changes
This is an iterim review, as I feel that the original sample(s) we're referencing should first be refactor, so the methods are more concrete and easy-to-understand

2021-07-28 09:45 UTC, ViktorSlavov requested changes

2021-07-28 09:45 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +### Scrolling the grid when a row is dragged to the top or bottom of it
This should be h4 and a bit shorter
```suggestion
#### Scrolling the grid on row drag
```

2021-07-28 09:45 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +Finally, we create method that will be used to handle the [`IgxDragDirective.dragMove`]({environment:angularApiUrl}/classes/igxdragdirective.html#dragmove) event (emitted for the dragged row). The me
```suggestion
Finally, we create a method that will be used to handle the [`IgxDragDirective.dragMove`]({environment:angularApiUrl}/classes/igxdragdirective.html#dragmove) event (emitted for the dragged row). The method will change the value of the property used in the `igxRowDragGhost` template and force a rerender.
```

2021-07-28 09:45 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +        this._draggedRow = e.dragData.rowData;
Indentation is off.
```suggestion
            this._draggedRow = e.dragData.rowData;
```

2021-07-28 09:45 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +```typescript
The indentation in the whole snippets seems a bit off

2021-07-28 09:45 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +@@if (igxName === 'IgxGrid') {
I think the whole section (so, just before "Improving UX in row drag scenarios") should be wrapped with `@@if (igxName === 'IgxGrid')`. With the current setup, you'd just have a lot of text and snippets (which we're not sure are correct) for the Tree and Hierarchical grids.
I believe that's the best solution for now - we can log an enhancement and add separate samples for Tree and Hierarchical grids later on.

2021-07-28 09:46 UTC, ViktorSlavov requested changes
Also, update the Grid => Row Drag entry in the components.yml, so it shows the topic as updated

2021-07-29 09:25 UTC, ViktorSlavov requested changes

2021-07-29 09:25 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +@@if (igxName === 'IgxHierarchicalGrid') {
Should be for base grid, instead of hGrid
```suggestion
@@if (igxName === 'IgxGrid') {
```

2021-07-29 09:25 UTC, ViktorSlavov commented on en/components/grids_templates/row-drag.md
> +        this.intervalSub.unsubscribe();
Indentation is off

2021-07-29 09:26 UTC, ViktorSlavov approved these changes

2021-07-29 09:57 UTC, merged