Update reactive forms topic
IgniteUI/igniteui-docfx pull request #2919
Opened 2021-07-27 08:58 UTC by jackofdiamond5

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-07-27 11:10 UTC, morbidiam commented
it all looks good to me

2021-07-28 06:09 UTC, wnvko requested changes
there is a redirect setup now in `en/web.config`, but there is not for `jp` and `kr`.

2021-07-28 06:20 UTC, morbidiam commented on en/components/angular-reactive-form-validation.md
> +Angular form validation is an integral technical process that verifies if any input provided by a user into a web-form is correct and complete. You can manage validation in a template-driven approach
@wnvko , done. I removed this one.

2021-07-28 13:19 UTC, jackofdiamond5 commented on en/components/angular-reactive-form-validation.md
> +When a form reset is performed, the `FormControl` members `touched`, `dirty`, etc can be updated through an API call. This will not reflect on the style of the `IgxInputGroupComponent` as the validit
Honestly this whole section seems like a filler to me, so I'll just get rid of it.

2021-07-29 05:28 UTC, wnvko submitted a review, later dismissed

2021-07-29 10:29 UTC, Lipata approved these changes

2021-07-29 10:30 UTC, merged