Add explicit-editor description
IgniteUI/igniteui-docfx pull request #2942
Opened 2021-08-02 11:39 UTC by dobromirts

Closes # 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-08-03 06:44 UTC, gedinakova requested changes

2021-08-03 06:44 UTC, gedinakova commented on README.md
> +<code-view explicit-editor="csb"</code-view>
Missing closing '>'.
```suggestion
<code-view explicit-editor="csb" ... ></code-view>
```

2021-08-03 06:44 UTC, gedinakova commented on README.md
> +<code-view explicit-editor="stackblitz"</code-view>
Same as above.

2021-08-03 07:21 UTC, gedinakova approved these changes

2021-08-04 08:35 UTC, zdrawku approved these changes

2021-08-04 08:35 UTC, merged