feat(grids): update Sorting topics with the newly added feature for templating sorting indicator
IgniteUI/igniteui-docfx pull request #3008
Opened 2021-11-04 09:34 UTC by viktorkombov

Closes #3006 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-11-11 09:00 UTC, kacheshmarova commented on en/components/grids_templates/sorting.md
> +If you want to customize the sorting indicator icon in the column header you could use custom templates. The Three Grid provides three directives for templating the indicators for all states of the c
There is a typo in TreeGrid name. ThreeGrid -> TreeGrid

2021-11-11 09:02 UTC, kacheshmarova reviewed
There is a typo in the TreeGrid name. ThreeGrid -> TreeGrid

2021-11-11 09:11 UTC, kacheshmarova submitted a review, later dismissed

2021-11-11 09:37 UTC, katherinedragieva approved these changes

2021-11-11 10:42 UTC, hanastasov requested changes

2021-11-11 10:42 UTC, hanastasov commented on en/components/grids_templates/sorting.md
> +If you want to customize the sorting indicator icon in the column header you could use custom templates. The Grid provides three directives for templating the indicators for all states of the column
Try to use more passive voice, instead of `you`, `we` or `I`:

The sorting indicator icon can be template...

2021-11-11 10:42 UTC, hanastasov commented on en/components/grids_templates/sorting.md
> +If you want to customize the sorting indicator icon in the column header you could use custom templates. The Grid provides three directives for templating the indicators for all states of the column
The following directives are available for templating the sorting indicator for any sorting state (Ascending, descending, none):

2021-11-11 12:14 UTC, kacheshmarova approved these changes

2021-11-12 08:26 UTC, hanastasov approved these changes

2021-11-12 08:28 UTC, katherinedragieva approved these changes

2021-11-12 08:29 UTC, merged