feat(grid): update how to use action-strip
IgniteUI/igniteui-docfx pull request #3009
Opened 2021-11-04 16:35 UTC by Svetloslav15

Closes #3007 

This PR needs the sample from [here](https://github.com/IgniteUI/igniteui-angular-samples/pull/2838), before merging.

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2021-11-05 09:48 UTC, hanastasov requested changes

2021-11-05 09:48 UTC, hanastasov commented on en/components/action-strip.md
> +### Row actions topic as part of the Grids section
Not needed to take the title so literally ;) Also, action-strip.md topic is not part of the Grids section - look where the grid topics are located and create a new one, where to put this content.

2021-11-05 10:04 UTC, kdinev requested changes

2021-11-05 10:04 UTC, kdinev commented on en/components/action-strip.md
> +    <igx-icon>edit</igx-icon>
indentation

2021-11-05 13:53 UTC, Aleksandyr commented
@Svetloslav15 @hanastasov IMO this topic has to be part of the existing one for the [actionSstrip](https://www.infragistics.com/products/ignite-ui-angular/angular/components/action-strip).
There is plenty of information which is not mentioned in the topic like the custom implementation and that the current implementation extends **igxGridActionBaseDirective** which might be misleading for the users.

2021-11-05 14:12 UTC, Aleksandyr requested changes

2021-11-05 14:12 UTC, Aleksandyr commented on en/components/grid/action-strip.md
> +The Grid component in Ignite UI for Angular provides the ability to use `ActionStrip` component to achieve row actions.
```suggestion
The grid component in Ignite UI for Angular provides the ability to use `ActionStrip` and utilize CRUD for row/cell components and row pinning. 
```

2021-11-05 14:12 UTC, Aleksandyr commented on en/components/grid/action-strip.md
> +By default, we are providing two grid action components:
```suggestion
Twо grid actions are provided by default:
```

2021-11-05 14:12 UTC, Aleksandyr commented on en/components/grid/action-strip.md
> +- [`IgxGridEditingActionsComponent`]({environment:angularApiUrl}/classes/igxgrideditingactionscomponent.html) - includes functionality and UI related to grid editing. It allows you to quickly toggle
```suggestion
- [`IgxGridEditingActionsComponent`]({environment:angularApiUrl}/classes/igxgrideditingactionscomponent.html) - includes functionality and UI specifically designed for the grid editing. It allows you to quickly toggle edit mode for cells or rows, depending on the [`rowEditable`]({environment:angularApiUrl}/classes/IgxGridComponent.html#rowEditable) option and row deletion of the grid.
```

2021-11-05 14:12 UTC, Aleksandyr commented on en/components/grid/action-strip.md
> +- [`IgxGridPinningActionsComponent`]({environment:angularApiUrl}/classes/igxgridpinningactionscomponent.html) - includes functionality and UI related to grid row pinning. It allows you to quickly pin
```suggestion
- [`IgxGridPinningActionsComponent`]({environment:angularApiUrl}/classes/igxgridpinningactionscomponent.html) - includes functionality and UI specifically designed for the grid row pinning. It allows you to quickly pin rows and navigate between pinned rows and their disabled counterparts.
```

2021-11-05 14:12 UTC, Aleksandyr commented on en/components/grid/action-strip.md
> +You can use the them or create custom component and then add it to the `ActionStrip`. If you want to use `ActionStrip` to achieve a Gmail scenario with row actions such as `delete`, `edit` and etc. Y
```suggestion
These components expose templates giving flexibility for customization. For instance, if we would like to use the `ActionStrip` for a Gmail scenario with row actions such as `delete`, `edit` and etc. You can simply create button component with `igx-icon`, add click event to it and insert it into the `igx-action-strip` component.
```

2021-11-05 14:12 UTC, hanastasov commented
> @Svetloslav15 @hanastasov IMO this topic has to be part of the existing one for the [actionSstrip](https://www.infragistics.com/products/ignite-ui-angular/angular/components/action-strip). There is plenty of information that is not mentioned in the topic like the custom implementation and that the current implementation extends **igxGridActionBaseDirective** which might be misleading for the users.

It is not a problem to duplicate the content in the original topic as well, but the initial requirement that made us open this PR is the demand to have such a topic under Grid section.

Of course the content in the grid section will be probably less than the original one, as it only needs to cover what is relevant for action strip within the grid.

2021-11-05 15:23 UTC, Aleksandyr requested changes

2021-11-05 15:25 UTC, Aleksandyr approved these changes

2021-11-08 08:11 UTC, kdinev requested changes

2021-11-08 08:11 UTC, kdinev commented on en/components/grid/action-strip.md
> +</igx-grid>
```suggestion
<igx-grid>
    <igx-action-strip #actionstrip>
        <igx-grid-pinning-actions></igx-grid-pinning-actions>
        <button title="Edit" igxButton="icon" igxRipple (click)='startEdit(actionstrip.context)'>
            <igx-icon>edit</igx-icon>
        </button>
        <button title="Delete" igxButton="icon" igxRipple *ngIf='!isDeleted(actionstrip.context)' (click)='actionstrip.context.delete()'>
            <igx-icon>delete</igx-icon>
        </button>
    </igx-action-strip>
</igx-grid>
```

2021-11-08 08:13 UTC, kdinev commented
Btw, I see that this is added to the `igx-grid` docs, but isn't the action strip usable within all our grids (flat, tree, hierarchical) and shouldn't this article be added to the grid template ones, hence be made available to all three grids?

2021-11-08 09:44 UTC, hanastasov requested changes
As already requested, content amy be moved under grids_templates, this way it will be reused among all grids.

Also, update the toc.yml files to include the new topic with NEW label.

PR should target vNext.

2021-11-08 13:10 UTC, closed without merging