input-group: add validation section
IgniteUI/igniteui-docfx pull request #3444
Opened 2022-12-08 17:00 UTC by RivaIvanova

Closes #3146 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [x] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [x] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [x] add inline `code blocks` for the names of classes / tags / properties
 - [x] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [x] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2022-12-09 14:27 UTC, kdinev requested changes

2022-12-09 14:27 UTC, kdinev commented on en/components/input-group.md
> +The following samples demonstrate how input validation could be achieved when using template-driven or reactive forms.
```suggestion
The following samples demonstrate how to configure input validation when using [template-driven](https://angular.io/guide/forms) or [reactive forms](https://angular.io/guide/reactive-forms).
```

2022-12-09 14:27 UTC, kdinev commented on en/components/input-group.md
> +<igx-input-group>
Include the wrapping form element in each code snippet, together with the submit button.

2022-12-09 14:27 UTC, kdinev commented on en/components/input-group.md
> +The following example uses two-way data binding and demonstrates how to inspect the control's state by exporting the `ngModel` to a local variable.
Also include an example on how to inspect general form validity through the ngForm. In general the check there would be perform in the submit button to make it enabled/disabled.

2022-12-09 14:27 UTC, kdinev commented on en/components/input-group.md
> +<form [formGroup]="registrationForm">
Again, include a submit button.

2022-12-09 14:27 UTC, kdinev commented on en/components/input-group.md
> +Some input fields may require custom validation and this could be achieved via custom validators. When the value is valid, the validator will return `null` and when the value is invalid, it will gene
I have left a review comment about the custom validation sample in the samples repo. There, you would be able to create an example of how one from control drives the validity of a different form control, or of the entire group.

2022-12-21 09:53 UTC, jackofdiamond5 approved these changes

2022-12-21 11:03 UTC, merged