Update guide for combo
IgniteUI/igniteui-docfx pull request #3973
Opened 2023-11-03 15:36 UTC by wnvko

Add notes in update guide about breaking changes in combo and simple combo.

Closes #3972 

### Checklist:
 
 - [ ] check topic's TOC/menu and paragraph headings
 - [ ] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [ ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [ ] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [ ] check if sample is working and fully visible in the topic
 - [ ] check if sample is working and fully visible in the StackBlitz
 - [ ] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2023-11-05 20:49 UTC, Lipata requested changes

2023-11-05 20:49 UTC, Lipata commented on en/components/general/update-guide.md
> +  // prior version 15.1.x
```suggestion
  // version 16.1.x
```

2023-11-05 20:49 UTC, Lipata commented on en/components/general/update-guide.md
> +  // after version 15.1.x
```suggestion
  // version 17.0.x
```

2023-11-05 20:49 UTC, Lipata commented on en/components/general/update-guide.md
> +
Can you add a paragraph, describing the change from oldSelection/newSelection to oldValue/newValue and also the fact that there are migrations for that?

2023-11-09 14:22 UTC, hanastasov commented
Closing in favour of https://github.com/IgniteUI/igniteui-docfx/pull/3980

2023-11-09 16:58 UTC, Lipata approved these changes

2023-11-09 17:33 UTC, Lipata approved these changes

2023-11-09 17:37 UTC, merged