docs(summaries): add new disable summaries section
IgniteUI/igniteui-docfx pull request #6011
Opened 2024-11-27 07:55 UTC by georgianastasov

Closes #6008 

### Checklist:
 
 - [x] check topic's TOC/menu and paragraph headings
 - [ ] [Include TOC topic labels](https://github.com/IgniteUI/igniteui-docfx/blob/master/README.md#include-toc-topic-labels) in topic content has a valuable update, it's new or considered as `preview`\ `beta`
 - [x] link to other topics using `../relative/path.md`
 - [ ] at the References section at the end of the topic add links to topics, samples, etc
 - [ ] reference API documentation instead of adding a section with API

<br />

 - [ ] use valid component names - [Data] Grid, `IgxSelectComponent`, `<igx-combo>`
 - [x] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
 - [x] add inline `code blocks` for the names of classes / tags / properties
 - [ ] add language descriptor for the ```code blocks```
 - [ ] check broken links (use browser add-on)
 - [x] check if sample is working and fully visible in the topic
 - [x] check if sample is working and fully visible in the StackBlitz
 - [x] check if code blocks match the code in StackBlitz demo

<br />

 - [ ] follow SEO guidelines to fill topic's metadata ([SEO guidelines](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWz9InT4FDlErHCumxsKGY4Bd8H03yhRWxDFk47luRz-_Q?e=S5wWcx))

<br />

 - [ ] do not resolve requested changes (leave that to the reviewer)
 - [ ] add `pending-localization` label when the review of the PR is done
 - [ ] add a member from the localization team to translate it

2025-01-15 20:02 UTC, kacheshmarova commented on en/components/grids_templates/summaries.md
If these empty lines can be omitted and still have the paragraph starting on a new line - that would be great.
![image](https://github.com/user-attachments/assets/0d719db2-48b0-4e7b-8150-bf25724ed576)

2025-01-15 20:08 UTC, kacheshmarova commented on en/components/grids_templates/summaries.md
> +
Same here with empty lines.

2025-01-21 14:43 UTC, radomirchev requested changes

2025-01-21 14:43 UTC, radomirchev commented on en/components/grids_templates/summaries.md
> +The [`disabledSummaries`]({environment:angularApiUrl}/classes/@@igTypeDoc.html#disabledSummaries) property provides precise control over the summary functions displayed for each column in the grid. T
property provides precise control over the summary functions displayed for each column in the grid. - this may paraphrase as: property provides precise per column control over the Ignite UI for Angular grid summary feature. This property enables the user to customize the summaries,...

In general: Ignite UI *framework* grid *feature* - when mentioning grid features, we need to avoid mentioning only the feature name without "grid", users are searching for: angular grid summaries or grid summaries

2025-01-21 14:43 UTC, radomirchev commented on en/components/grids_templates/summaries.md
> +Below are examples demonstrating the use of the `disabledSummaries` property for different columns and different summaries.
different columns and different summaries. - different columns and summaries?

2025-01-24 14:53 UTC, kacheshmarova approved these changes

2025-01-27 09:04 UTC, radomirchev approved these changes

2025-01-31 08:01 UTC, merged